INSERT INTO PACIENTE VALUES (1,'Jorge',"Cárdenas","Cárdenas","Hombre","1999-11-05","Av. Siempre Viva N303 Colonia Centro, Atlacomulco, Edo de México",9931423412,"Soltero","Católica","Atlacomulco, Edo de México");
INSERT INTO PACIENTE VALUES (2,'Melissa Monserrat',"Monsalvo","Bolaños","Mujer","1995-03-12","Av. Universidad N23, Copilco, Coyoacán, CDMX",5532515233,"Casada","Cristiana","Coyoacán, CDMX");
INSERT INTO PACIENTE VALUES (3,'Samuel Arturo',"Garrido","Sánchez","Hombre","1999-05-07","Calle Jalapa Esq. Nacajuca Fraccionamiento Cunduacán 2000, Cunduacán, Tabasco 86690",9141203710,"Soltero","Atea","Villahermosa, Tabasco");


-- Imaginemos un paciente con solo datos básicos

INSERT INTO PACIENTE(Nombre,ApellidoPat,ApellidoMat,telefono) VALUES("David","Garrido","Sanchez",9141235231)
-- Registro de médico

INSERT INTO MEDICO VALUES (12345678,"Nerio","Gallegos","Jiménez",MD5("tabasco"));
INSERT INTO MEDICO VALUES (87654321,"Carmela","Norio","Pambazo",MD5("edomex123"));
INSERT INTO MEDICO VALUES (19462953,"Ricardo","Porfirio","Díaz",MD5("CdMx+542"));

-- Generar antecedentes para algunos pacientes:

INSERT INTO ANTECEDENTES VALUES (2,"Lorem ipsum dolor sit amet consectetur adipiscing elit sed, eleifend curabitur vestibulum auctor sodales bibendum ad at, viverra nibh nec feugiat libero ac torquent. Quisque mus bibendum","Ornare velit natoque penatibus dictumst mus nulla fermentum cubilia sodales libero, interdum consequat nam tincidunt justo","vel himenaeos maecenas sagittis sed, phasellus porta in vulputate nostra sociosqu ad varius cursus.","Morbi felis interdum lacinia leo penatibus ante class augue, libero purus diam semper congue","Ridiculus convallis natoque, ligula quisque lobortis cum posuere dignissim vulputate")

INSERT INTO ANTECEDENTES VALUES (1,"Ornare velit natoque penatibus dictumst mus nulla fermentum cubilia sodales libero, interdum consequat nam tincidunt justo","vel himenaeos maecenas sagittis sed, phasellus porta in vulputate nostra sociosqu ad varius cursus.","Morbi felis interdum lacinia leo penatibus ante class augue, libero purus diam semper congue","Lorem ipsum dolor sit amet consectetur adipiscing elit sed, eleifend curabitur vestibulum auctor sodales bibendum ad at, viverra nibh nec feugiat libero ac torquent. Quisque mus bibendum","Ridiculus convallis natoque, ligula quisque lobortis cum posuere dignissim vulputate")

INSERT INTO DIAGNOSTICO VALUES (1,"2019-12-01","")




-- INSERSIÓN EN DIAGNÍSTICO

INSERT INTO DIAGNOSTICO(fechainicio,Nombre,Descripción) VALUES ("2019-12-01","CONJUNTIVITIS AGUDA","SE LLEGÓ CON CASO DE CONJUNTIVITUS RELATIVO A LA ÉPOCA DEL AÑO");
INSERT INTO DIAGNOSTICO(fechainicio,Nombre,Descripción) VALUES ("2019-11-05","NEUMONÍA CRÓNICA","CAUSAS DE CONTAGIO POR ACERCAMIENTO A LA ZONA");

SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, PACIENTE.telefono, DIAGNOSTICO.NOMBRE, DIAGNOSTICO.FECHAINICIO FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO WHERE PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=1;


INSERT INTO CONSULTAGENERAL(DIAGNOSTICO_idDIAGNOSTICO,MEDICO_CedProf,Descripcion,FechaHora) VALUES ('1','12345678','Consulta general de rutina',"2019-12-01 14:12:11")

INSERT INTO NOTA_MEDICA(PADECIMIENTO,
	EXPLOFISICA,
	TRATAMIENTO,
	PLAN,
	TEMPERATURA,
	TA,
	FC,
	FR,
	OXIOMETRIA,
	PESO,
	TALLA,
	CONSULTAGENERAL_MEDICO_CedProf,
	CONSULTAGENERAL_idCONSULTAGENERAL,
	CONSULTAGENERAL_DIAGNOSTICO_idDIAGNOSTICO) 
VALUES ("LOREM",
	"IPSOUMSSS",
	"NO SE ENCONTRÓ NADA",
	"UNAS CHELAS AL DÍA",
	36.2,
	1300,
	54,
	89,
	44,
	102.43,
	180,
	12345678,
	1,
	1)

INSERT INTO NOTA_MEDICA(PADECIMIENTO,EXPLOFISICA,TRATAMIENTO,PLAN,TEMPERATURA,TA,FC,FR,OXIOMETRIA,PESO,TALLA,CONSULTAGENERAL_MEDICO_CedProf,CONSULTAGENERAL_idCONSULTAGENERAL,CONSULTAGENERAL_DIAGNOSTICO_idDIAGNOSTICO) VALUES ("LOREM","IPSOUMSSS","NO SE ENCONTRÓ NADA","UNAS CHELAS AL DÍA",40.1,1030,54,89,44,102.43,180,12345678,1,1);


SELECT PACIENTE.NOMBRE,DIAGNOSTICO.NOMBRE,CONSULTAGENERAL_MEDICO_CedProf,

INSERT INTO NOTA_MEDICA(PADECIMIENTO, EXPLOFISICA, TRATAMIENTO, PLAN, TEMPERATURA, TA, FC, FR, OXIOMETRIA, PESO, TALLA, CONSULTAGENERAL_idCONSULTAGENERAL, CONSULTAGENERAL_DIAGNOSTICO_idDIAGNOSTICO) VALUES ("SE ECONTRÓ CON REGISTRO DE TORCEDURA DE TOBILLO","MORETONES EN EL COSTADO IZQUIERDO","TOMAR 5 TABLETAS DE PARECETAMOL","CULTIVO FANGILAR CADA SEMANA",45.4,1133,55,120,50,110.33,145,1,1);


SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, MEDICO.NOMBRE, DIAGNOSTICO.NOMBRE, CONSULTAGENERAL.FechaHora,NOTA_MEDICA.TA,NOTA_MEDICA.FR FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO INNER JOIN NOTA_MEDICA INNER JOIN CONSULTAGENERAL ON CONSULTAGENERAL.idCONSULTAGENERAL = NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL INNER JOIN MEDICO WHERE NOTA_MEDICA.idNOTAMEDICA=1

SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, MEDICO.NOMBRE, DIAGNOSTICO.NOMBRE, CONSULTAGENERAL.FechaHora,NOTA_MEDICA.TA,NOTA_MEDICA.FR FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO INNER JOIN NOTA_MEDICA INNER JOIN CONSULTAGENERAL ON CONSULTAGENERAL.idCONSULTAGENERAL = NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL INNER JOIN MEDICO ON MEDICO.CEDPROF=CONSULTAGENERAL.MEDICO_CedProf WHERE NOTA_MEDICA.idNOTAMEDICA=1




SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, MEDICO.NOMBRE, DIAGNOSTICO.NOMBRE, CONSULTAGENERAL.FechaHora,NOTA_MEDICA.TA,NOTA_MEDICA.FR FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO INNER JOIN NOTA_MEDICA ON NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL = CONSULTAGENERAL.idCONSULTAGENERAL INNER JOIN CONSULTAGENERAL ON CONSULTAGENERAL.idCONSULTAGENERAL = NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL INNER JOIN MEDICO ON MEDICO.CEDPROF=CONSULTAGENERAL.MEDICO_CedProf HERE NOTA_MEDICA.idNOTAMEDICA=1;


SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, MEDICO.NOMBRE, DIAGNOSTICO.NOMBRE, CONSULTAGENERAL.FechaHora,NOTA_MEDICA.TA,NOTA_MEDICA.FR FROM PACIENTE 
INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE 
INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO 
INNER JOIN NOTA_MEDICA ON NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL = CONSULTAGENERAL.idCONSULTAGENERAL
INNER JOIN CONSULTAGENERAL ON DIAGNOSTICO.idDIAGNOSTICO = CONSULTAGENERAL.DIAGNOSTICO_idDIAGNOSTICO
INNER JOIN MEDICO ON MEDICO.CEDPROF=CONSULTAGENERAL.MEDICO_CedProf 
WHERE NOTA_MEDICA.idNOTAMEDICA=1;



SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, MEDICO.NOMBRE, DIAGNOSTICO.NOMBRE, CONSULTAGENERAL.FechaHora,NOTA_MEDICA.TA,NOTA_MEDICA.FR,NOTA_MEDICA.TRATAMIENTO
FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE 
INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO 
INNER JOIN CONSULTAGENERAL ON DIAGNOSTICO.idDIAGNOSTICO = CONSULTAGENERAL.DIAGNOSTICO_idDIAGNOSTICO
INNER JOIN NOTA_MEDICA ON CONSULTAGENERAL.idCONSULTAGENERAL = NOTA_MEDICA.CONSULTAGENERAL_idCONSULTAGENERAL 
INNER JOIN MEDICO ON MEDICO.CEDPROF=CONSULTAGENERAL.MEDICO_CedProf 
WHERE NOTA_MEDICA.idNOTAMEDICA=1;



