-- JOINS PARA SELECCIONAR DATOS:
SELECT PACIENTE.NOMBRE, PACIENTE.SEXO, ANTECEDENTES.AntTerap FROM PACIENTE INNER JOIN ANTECEDENTES ON PACIENTE.idPACIENTE=ANTECEDENTES.PACIENTE_idPACIENTE;

ALTER TABLE PACIENTEDIAGNOSTICO DROP INDEX PACIENTE_idPACIENTE_UNIQUE;

-- PARA SELECCIONAR LA ENFERMEDAD ASOCIADA

SELECT PACIENTE.NOMBRE, PACIENTE.ApellidoPat, PACIENTE.telefono, DIAGNOSTICO.NOMBRE, DIAGNOSTICO.FECHAINICIO FROM PACIENTE INNER JOIN PACIENTEDIAGNOSTICO ON PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=PACIENTE.idPACIENTE INNER JOIN DIAGNOSTICO ON DIAGNOSTICO.idDIAGNOSTICO=PACIENTEDIAGNOSTICO.DIAGNOSTICO_idDIAGNOSTICO WHERE PACIENTEDIAGNOSTICO.PACIENTE_idPACIENTE=1;

SELECT nombre,apellidopat,sexo,fechanacimiento,telefono FROM paciente WHERE sexo="Hombre";

SELECT * FROM MEDICO WHERE CONTRASENA=MD5("tabasco");